# Generated by Django 4.1.7 on 2023-03-12 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_order_email_order_fullname_order_phone'),
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(default='123', max_length=3, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.CharField(default='12', max_length=2, verbose_name='Месяц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='sad asd', max_length=200, verbose_name='Имя владельца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='number',
            field=models.CharField(default='1234123412341234', max_length=20, verbose_name='Номер карты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='years',
            field=models.CharField(default='1231', max_length=4, verbose_name='Год'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order_app.order', verbose_name='Заказ'),
        ),
    ]
