# Generated by Django 4.1.7 on 2023-03-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_remove_order_card_number_remove_order_paid_and_more'),
        ('payment_app', '0004_payment_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='years',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='order_app.order', verbose_name='Заказ'),
        ),
    ]
