# Generated by Django 4.1.7 on 2023-03-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0004_rename_total_price_basketproduct_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketproduct',
            old_name='price',
            new_name='fixed_price',
        ),
    ]
