# Generated by Django 4.1.7 on 2023-03-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0006_basketproduct_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='session_key',
            field=models.CharField(max_length=200),
        ),
    ]
