# Generated by Django 4.1.7 on 2023-03-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0018_alter_review_author_alter_review_email_and_more'),
        ('order_app', '0002_alter_order_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='shop_app.product', verbose_name='Товар'),
        ),
    ]
