# Generated by Django 4.1.7 on 2023-03-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='qwe@qwe.qwe', max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='fullName',
            field=models.CharField(default='qwe qwe', max_length=200, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='+79123912392', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
