# Generated by Django 4.1.7 on 2023-03-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_order_email_order_fullname_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_code',
        ),
    ]
