# Generated by Django 4.1.7 on 2023-03-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_rename_count_orderproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_delivery', models.CharField(default='Стандартная', max_length=100, verbose_name='Название')),
                ('type_delivery', models.CharField(default='ordinary', max_length=100, verbose_name='Тип доставки')),
                ('price_delivery', models.IntegerField(default=200, verbose_name='Цена доставки')),
                ('limit', models.IntegerField(default=2000)),
                ('above_price_limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default='ordinary', max_length=30, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('1', 'Онлайн с моей картой'), ('2', 'Онлайн сторонней карты')], default='1', max_length=30, verbose_name='Тип оплаты'),
        ),
    ]
