# Generated by Django 4.1.7 on 2023-03-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_delivery_alter_order_delivery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='above_price_limit',
            field=models.IntegerField(default=0, verbose_name='Цена выше границы'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='limit',
            field=models.IntegerField(default=2000, verbose_name='Граница общей стоимости'),
        ),
    ]
