# Generated by Django 4.1.7 on 2023-03-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0009_alter_delivery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Delivery'},
        ),
    ]
