# Generated by Django 4.1.7 on 2023-03-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
