# Generated by Django 4.1.7 on 2023-03-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_alter_specification_title_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
    ]
