# Generated by Django 4.1.7 on 2023-03-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0013_rename_name_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='shop_app.product', verbose_name='Product'),
        ),
    ]
