# Generated by Django 4.1.7 on 2023-03-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_alter_specification_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='date',
        ),
    ]
