# Generated by Django 4.1.7 on 2023-03-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_rename_created_at_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(default='asd', max_length=100, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default=None, max_length=100, null=True, verbose_name='Email'),
        ),
    ]
