# Generated by Django 4.1.7 on 2023-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_remove_review_user_review_author_review_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(default=None, max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(default=None, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, default=None, verbose_name='Text'),
        ),
    ]
