# Generated by Django 4.1.7 on 2023-03-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0019_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
