# Generated by Django 4.1.7 on 2023-03-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0022_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rate',
            new_name='rating',
        ),
    ]
