# Generated by Django 4.1.7 on 2023-03-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0023_rename_rate_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='rate',
        ),
    ]
