# Generated by Django 4.1.7 on 2023-04-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0024_rename_rating_review_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='available_quantity',
        ),
    ]
